# Generated by Django 5.2.6 on 2026-01-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0023_googlecredentials_google_account_email'),
        ('payments', '0003_alter_stripesubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='auths.etablissement'),
        ),
    ]
