steps:
  - id: build-docker-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_TAG}'
      - '-t'
      - '${_IMAGE_NAME}'
      - '-f'
      - './Dockerfile'
      - '.'
  - id: extract-static-files
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - |
        docker create --name static_helper ${_IMAGE_NAME}
        docker cp static_helper:/app/staticfiles .
        docker rm static_helper
  - id: push-image-to-artifact-registry
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_TAG}'
  - id: push-static-files-to-bucket
    name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-d"
      - "./staticfiles/"
      - "gs://starshield-static"

images:
  - 'europe-west9-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _REPO_NAME: production-builds
    _IMAGE_NAME: web-app
    _TAG: latest
    