steps:
  - id: build-docker-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_IMAGE_NAME}'
      - '-f'
      - './Dockerfile'
      - '.'

  - id: extract-static-files
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - |
        docker create --name static_helper ${_IMAGE_NAME}
        docker cp static_helper:/app/staticfiles .
        docker rm static_helper
    waitFor: ['build-docker-image']

  - id: push-static-files-to-bucket
    name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-d"
      - "./staticfiles/"
      - "gs://starshield-static"
    waitFor: ['extract-static-files']

  - id: push-image-to-artifact-registry
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
    waitFor: ['build-docker-image']

  - id: deploy-to-cloud-run-webapp
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - '${_WEBAPP_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--region'
      - '${_REGION}'
    waitFor: ['push-image-to-artifact-registry']
    
  - id: deploy-to-cloud-run-tasks-api
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - '${_TASKS_API_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--region'
      - '${_REGION}'
    waitFor: ['push-image-to-artifact-registry']

  - id: execute-migrations-job
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - ${_MIGRATE_JOB_NAME}
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--region=${_REGION}'
      - '--execute-now'
      - '--wait'
    waitFor: ['push-image-to-artifact-registry']

options:
  logging: CLOUD_LOGGING_ONLY
    