# Generated by Django 5.2.6 on 2025-10-15 09:06

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0003_remove_user_entreprise_delete_entreprise"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredentials",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_valid", models.BooleanField(default=False)),
                ("token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_uri", models.TextField()),
                ("client_id", models.TextField()),
                ("client_secret", models.TextField()),
                ("scopes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("google_business_manager_account_id", models.CharField(max_length=255)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "review_threshold",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Minimum rating that triggers a Google review redirect.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "google_credentials",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auths.googlecredentials"),
                ),
            ],
        ),
    ]
