# Generated by Django 5.2.6 on 2025-10-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_googlecredentials_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='google_credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='auths.googlecredentials'),
        ),
    ]
