# Generated by Django 5.2.6 on 2025-10-15 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0007_remove_etablissement_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etablissement",
            old_name="google_credentials",
            new_name="google_credential",
        ),
        migrations.AlterField(
            model_name="googlecredentials",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_credential",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
