# Generated by Django 5.2.6 on 2025-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0015_etablissement_target_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="review_accent_color",
            field=models.CharField(
                default="#0b5ed7",
                help_text="Couleur d'accent pour la page de feedback (format hexadécimal).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="review_show_etablissement_pill",
            field=models.BooleanField(
                default=True, help_text="Afficher ou masquer le badge avec le nom de l'établissement."
            ),
        ),
    ]
