# Generated by Django 5.2.6 on 2025-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0017_etablissement_qr_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='qr_color_mask',
            field=models.CharField(choices=[('solid', 'Solide'), ('round_radial', 'Dégradé radial rond'), ('square_radial', 'Dégradé radial carré'), ('horizontal_gradiant', 'Dégradé horizontal'), ('vertical_gradiant', 'Dégradé vertical')], default='solid', help_text='Style de masque de couleur pour le QR code.', max_length=20),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='qr_fill_color_secondary',
            field=models.CharField(default='#000000', help_text='Couleur secondaire pour les dégradés (format hexadécimal).', max_length=7),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='qr_style',
            field=models.CharField(choices=[('square', 'Carré'), ('square_spaced', 'Carré espacé'), ('rounded', 'Arrondi'), ('circle', 'Cercle')], default='square', help_text='Style des modules du QR code.', max_length=20),
        ),
    ]
