# Generated by Django 5.2.6 on 2025-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0018_etablissement_qr_color_mask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecredentials",
            name="has_invalid_grants",
            field=models.BooleanField(default=False),
        ),
    ]
