# Generated by Django 5.2.6 on 2026-01-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0022_etablissement_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecredentials",
            name="google_account_email",
            field=models.EmailField(
                blank=True, help_text="Email of the connected Google account", max_length=254, null=True
            ),
        ),
    ]
