# Generated by Django 5.2.6 on 2026-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0025_alter_etablissement_roulette_spin_cooldown_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='review_filtering_enabled',
            field=models.BooleanField(default=True, help_text="Activer le filtrage d'avis basé sur le seuil de redirection."),
        ),
    ]
