# Generated by Django 5.2.6 on 2025-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_reviewanalytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewanalytics",
            name="type",
            field=models.CharField(
                choices=[
                    ("review_page_consulted", "Review Page Consulted"),
                    ("external_feedback", "External Feedback"),
                    ("internal_feedback", "Internal Feedback"),
                ],
                max_length=255,
            ),
        ),
    ]
