# Generated by Django 5.2.6 on 2026-02-07 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_review_reply_comment_review_reply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='google_review_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply_type',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('google', 'Google')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='writen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
