# Generated by Django 5.2.6 on 2026-02-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("fetch_reviews_all", "Fetch Reviews All"),
                    ("fetch_reviews_refresh", "Fetch Reviews Refresh"),
                    ("fetch_stats", "Fetch Stats"),
                    ("fetch_reviews", "Fetch Reviews"),
                    ("generate_ai_responses", "Generate AI Responses"),
                ],
                max_length=50,
            ),
        ),
    ]
