# Generated by Django 5.2.6 on 2026-01-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0023_googlecredentials_google_account_email"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_subscriptions",
                to="auths.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="grace_period_end",
            field=models.DateTimeField(
                blank=True, help_text="When cancelled subscription should deactivate etablissement", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="subscription_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stripesubscription",
            unique_together={("etablissement", "subscription_id")},
        ),
    ]
