# Generated by Django 5.2.6 on 2026-01-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0023_googlecredentials_google_account_email"),
        ("payments", "0002_change_stripe_subscription_to_etablissement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stripesubscription",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="etablissement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_subscription",
                to="auths.etablissement",
            ),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="subscription_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="current_period_end",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="current_period_start",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="grace_period_end",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="payment_method_brand",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="payment_method_last4",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="user",
        ),
    ]
