# Generated by Django 5.2.6 on 2026-02-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0033_alter_etablissement_active'),
        ('payments', '0004_alter_stripesubscription_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='auths.etablissement'),
        ),
    ]
