# Generated by Django 5.2.6 on 2026-01-21 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roulette", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rouletteprize",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="rouletteprize",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="rouletteprize",
            name="probability",
            field=models.IntegerField(
                help_text="Probability percentage (min 1%)",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.RemoveField(
            model_name="rouletteprize",
            name="order",
        ),
    ]
