# Generated by Django 5.2.6 on 2025-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_reviewanalytics_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanalytics',
            name='type',
            field=models.CharField(choices=[('feedback_viewed', 'Feedback Viewed'), ('feedback_external', 'External Feedback'), ('feedback_internal_viewed', 'Internal Feedback Viewed'), ('feedback_internal_submitted', 'Internal Feedback Submitted')], max_length=255),
        ),
    ]
