"""
Django settings for starshield project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from configurations import Configuration
import os
from django_components import ComponentsSettings
from starshield.logging_formatter import ColoredFormatter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


class Base(Configuration):
    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

    # SECURITY
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "VERY_INSECURE_SECRET_KEY")
    ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        #
        # Auths app
        "auths",
        "allauth",
        "allauth.account",
        "allauth.socialaccount",
        "allauth.socialaccount.providers.google",
        #
        # Third party apps
        "django_htmx",
        "django_components",
        #
        # Frontend apps
        "frontend.dashboard",
        "frontend.reviews",
        "frontend.roulette",
        #
        # API apps
        "tasks_api",
        "payments",
    ]

    # API-friendly middleware
    CORE_MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "allauth.account.middleware.AccountMiddleware",
    ]

    MIDDLEWARE = [
        *CORE_MIDDLEWARE,
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.LoginRequiredMiddleware",
        "django_htmx.middleware.HtmxMiddleware",
        "starshield.middleware.CustomMessageMiddleware",
        "starshield.middleware.EtablissementMiddleware",
    ]

    ROOT_URLCONF = "starshield.urls"

    DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [BASE_DIR / "templates"],
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
                "builtins": [
                    "django_components.templatetags.component_tags",
                ],
                "loaders": [
                    (
                        "django.template.loaders.cached.Loader",
                        [
                            "django.template.loaders.filesystem.Loader",
                            "django.template.loaders.app_directories.Loader",
                            "django_components.template_loader.Loader",
                        ],
                    ),
                ],
            },
        },
    ]

    COMPONENTS = ComponentsSettings(
        dirs=[BASE_DIR / "components"],
    )

    WSGI_APPLICATION = "starshield.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/5.2/ref/settings/#databases
    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    # Auths

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    AUTH_USER_MODEL = "auths.User"
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
        "allauth.account.auth_backends.AuthenticationBackend",
    ]

    LOGIN_REDIRECT_URL = "dashboard:accueil"
    LOGOUT_REDIRECT_URL = "account_login"
    LOGIN_URL = "account_login"
    LOGIN_EXEMPT_PATHS = ()

    ACCOUNT_USER_MODEL_USERNAME_FIELD = None
    ACCOUNT_SESSION_REMEMBER = True
    ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
    ACCOUNT_LOGIN_METHODS = {"email"}

    # Account on get settings
    SOCIALACCOUNT_LOGIN_ON_GET = True
    ACCOUNT_LOGOUT_ON_GET = True
    ACCOUNT_CONFIRM_EMAIL_ON_GET = True

    # Account email verification
    ACCOUNT_EMAIL_VERIFICATION = "mandatory"
    ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

    # Account Only one email
    ACCOUNT_CHANGE_EMAIL = True

    # Account email verification by code instead of link
    ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True

    # Custom account adapter for email styling
    ACCOUNT_ADAPTER = "starshield.account_adapter.CustomAccountAdapter"

    # Internationalization
    # https://docs.djangoproject.com/en/5.2/topics/i18n/

    LANGUAGE_CODE = "fr-fr"
    TIME_ZONE = "Europe/Paris"
    USE_I18N = True
    USE_TZ = True

    # URLS
    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]

    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

    # Task configuration
    TASK_MAX_RETRIES = 3
    TASK_TIMEOUT_SECONDS = 300  # 5 minutes

    # Brevo Email Configuration
    BREVO_SENDER_EMAIL = "noreply@starshield.pro"
    BREVO_SENDER_NAME = "StarShield"
    DEFAULT_FROM_EMAIL = BREVO_SENDER_EMAIL

    # Logging configuration


class Dev(Base):
    DEBUG = True

    WEBSITE_URL = "http://localhost:8000"

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

    # Email
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    # EMAIL_BACKEND = "starshield.email_backends.BrevoEmailBackend"
    # BREVO_API_KEY = "keykey"

    # STRIPE (test keys)
    STRIPE_PUBLIC_KEY = "pk_test_51SQXa9LTXmr2kgo1d0xybTC83CpckGWwAJgmg3So7zexggtedDp04OTZRf57KAtpqGZxqkrWcUxrFHbXjjgYopb300eENE18ue"
    STRIPE_SECRET_KEY = "sk_test_51SQXa9LTXmr2kgo1PCSTaSVZlh60CUaEkqdMifTatyZYDoB1SYBv1TqiLwc0x1GjG5CcVIREDf5IKqOK7rM7yfQ900QgpOdrTa"
    STRIPE_WEBHOOK_SECRET = "whsec_1a33b01f5f912d07f415cce17a6a55572f51f681e91ae2a077a78d57335078ba"

    # Google OAuth
    GOOGLE_OAUTH_CLIENT_ID = "621365538525-pmqljdfrvshf91c3dn3aqbe62k5l5909.apps.googleusercontent.com"
    GOOGLE_OAUTH_CLIENT_SECRET = "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"
    GOOGLE_OAUTH_GMB_SCOPES = [
        "https://www.googleapis.com/auth/business.manage",
        "https://www.googleapis.com/auth/userinfo.email",
        "openid",
    ]
    SOCIALACCOUNT_PROVIDERS = {
        "google": {
            "APP": {
                "client_id": GOOGLE_OAUTH_CLIENT_ID,
                "secret": GOOGLE_OAUTH_CLIENT_SECRET,
                "key": "",
            },
            "SCOPE": ["profile", "email"],
            "EMAIL_AUTHENTICATION": True,
            "EMAIL_VERIFICATION": "none",
        }
    }

    STRIPE_PRODUCTS = {
        "basic_subscription": {
            "product_id": "prod_Th3YAxKCSwFz7C",
            "monthly": "price_1Sp8GTLTXmr2kgo15d4HWHCa",
            "trimestrial": "price_1SrecTLTXmr2kgo1asA4ew0i",
            "yearly": "price_1Sp8DyLTXmr2kgo1SZyuntfr",
        },
    }

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "%(message)s",
            },
            "colored": {
                "()": ColoredFormatter,
                "format": "%(asctime)s | %(levelname)s | %(name)s | %(message)s",
                "datefmt": "%H:%M:%S",
            },
            "verbose": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "colored",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "loggers": {
            # App loggers - don't propagate to root to avoid duplicates
            "auths": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "payments": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "tasks_api": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "frontend": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            # Django framework logger - don't propagate to avoid duplicates
            "django": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }


class Prod(Base):
    DEBUG = False

    # login with google redirect uri protocol
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

    # Trust Cloud Run proxy headers for HTTPS detection
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    WEBSITE_URL = f"https://{os.getenv('WEBSITE_URL', 'app.starshield.pro')}"
    GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID", "")
    GCP_PROJECT_REGION = os.getenv("GCP_PROJECT_REGION", "")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "starshield_webapp",
            "USER": os.getenv("DB_PROD_USER"),
            "PASSWORD": os.getenv("DB_PROD_PASSWORD"),
            "HOST": f"/cloudsql/{os.getenv('DB_PROD_HOST')}",
            "PORT": 5432,
            "CONN_MAX_AGE": 600,
            "OPTIONS": {
                "connect_timeout": 10,
                "keepalives_idle": 30,
                "keepalives_interval": 10,
                "keepalives_count": 5,
            },
        }
    }

    # Google Cloud Storage
    GS_DEFAULT_BUCKET_NAME = "starshield-default"
    GS_STATIC_BUCKET_NAME = "starshield-static"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_DEFAULT_BUCKET_NAME,
                "project_id": GCP_PROJECT_ID,
                "default_acl": "publicRead",
                "querystring_auth": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://storage.googleapis.com/{GS_DEFAULT_BUCKET_NAME}/"
    STATIC_URL = f"https://storage.googleapis.com/{GS_STATIC_BUCKET_NAME}/"

    # Cloud Tasks configuration
    CLOUD_TASKS_SERVICE_ACCOUNT = "tasks-agent@starshield-app.iam.gserviceaccount.com"
    TASKS_API_BASE_URL = os.getenv("TASKS_API_BASE_URL", "http://localhost:8001")
    TASKS_API_QUEUE_NAME = "tasks-api"

    # Email
    EMAIL_BACKEND = "starshield.email_backends.BrevoEmailBackend"
    BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")

    # Stripe
    STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "")
    STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
    STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

    # Google OAuth
    GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
    GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")
    GOOGLE_OAUTH_GMB_SCOPES = [
        "https://www.googleapis.com/auth/business.manage",
        "https://www.googleapis.com/auth/userinfo.email",
        "openid",
    ]

    # Google KMS
    GOOGLE_KMS_KEY_RING_ID = "starshield-keys"

    SOCIALACCOUNT_PROVIDERS = {
        "google": {
            "APP": {
                "client_id": GOOGLE_OAUTH_CLIENT_ID,
                "secret": GOOGLE_OAUTH_CLIENT_SECRET,
                "key": "",
            },
            "SCOPE": ["profile", "email"],
            "EMAIL_AUTHENTICATION": True,
            "EMAIL_VERIFICATION": "none",
        }
    }

    STRIPE_PRODUCTS = {
        "basic_subscription": {
            "product_id": "prod_TnSZAJHkKpEyON",
            "monthly": "price_1SreSiPuCLDC9hxjRhhONOHs",
            "trimestrial": "price_1SreT9PuCLDC9hxjzuTLQnir",
            "yearly": "price_1SreTNPuCLDC9hxjvW6yG3fP",
        },
    }
