"""
Django settings for starshield project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from configurations import Configuration
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

class Base(Configuration):
    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

    # SECURITY
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
    ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS').split(',')


    # Application definition



    THIRD_PARTY_APPS = [
        'django_tenants',
        'django_htmx',
        'tailwind',
    ]

    SHARED_APPS = [
        'auths',
        "theme",
    ]

    TENANT_APPS = [
        'apps.users',
        'apps.reviews',
        'apps.roulette',
    ]

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',

        *THIRD_PARTY_APPS,
        *SHARED_APPS,
        *TENANT_APPS,
    ]

    MIDDLEWARE = [
        'django_tenants.middleware.main.TenantMainMiddleware',
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.LoginRequiredMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        "django_htmx.middleware.HtmxMiddleware",
    ]

    ROOT_URLCONF = 'starshield.urls'



    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'starshield.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': "db",
            'PORT': os.getenv('POSTGRES_PORT'),
        }
    }
    DATABASE_ROUTERS = (
        'django_tenants.routers.TenantSyncRouter',
    )
    TENANT_MODEL = 'auths.Entreprise'
    TENANT_DOMAIN_MODEL = 'auths.DomaineEntreprise'
    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


    # Auths

    AUTH_PASSWORD_VALIDATORS = [
        {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
        {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
        {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
        {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
    ]

    AUTH_USER_MODEL = 'users.User'
    LOGIN_REDIRECT_URL = '/'
    LOGOUT_REDIRECT_URL = '/'
    LOGIN_URL = 'auths:login'
    LOGIN_EXEMPT_PATHS = (
        '/auth/login/',
        '/auth/signup/',
        '/admin/login/',
        '/admin/logout/',
        '/admin/password_reset/',
    )


    # Internationalization
    # https://docs.djangoproject.com/en/5.2/topics/i18n/

    LANGUAGE_CODE = 'fr-fr'
    TIME_ZONE = 'Europe/Paris'
    USE_I18N = True
    USE_TZ = True


    # URLS

    WEBAPP_DOMAIN = os.getenv('WEBAPP_DOMAIN')
    STATIC_URL = 'static/'

    # Misc

    TAILWIND_APP_NAME = 'theme'

class Dev(Base):
    DEBUG = True

class Prod(Base):
    DEBUG = False

