# Generated by Django 5.2.6 on 2026-02-05 14:52

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roulette", "0002_alter_rouletteprize_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rouletteprize",
            name="probability",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Probability percentage (min 0.01%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
