# Generated by Django 6.0.2 on 2026-02-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_alter_rouletteprize_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettespin',
            name='prize_icon',
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roulettespin',
            name='prize_name',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roulettespin',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spins', to='roulette.rouletteprize'),
        ),
    ]
