# Generated by Django 5.2.6 on 2025-10-15 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0006_remove_etablissement_google_business_manager_account_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etablissement",
            name="name",
        ),
    ]
