# Generated by Django 5.2.6 on 2025-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0021_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
