# Generated by Django 5.2.6 on 2026-02-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0030_etablissement_ai_response_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the week')),
                ('short_summary', models.TextField(blank=True, default='', help_text='Short preview for the card')),
                ('summary_text', models.TextField(help_text='AI-generated full report')),
                ('advice_text', models.TextField(blank=True, default='', help_text='AI-generated advice section')),
                ('metrics_data', models.JSONField(blank=True, default=dict, help_text='Raw metrics used for generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='auths.etablissement')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'indexes': [models.Index(fields=['etablissement', '-week_start_date'], name='auths_weekl_etablis_33f87c_idx')],
                'unique_together': {('etablissement', 'week_start_date')},
            },
        ),
    ]
