# Generated by Django 5.2.6 on 2026-02-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0032_alter_qrcode_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
