# Generated by Django 6.0.2 on 2026-02-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0033_alter_etablissement_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='review_filtering_enabled',
            field=models.BooleanField(default=False, help_text="Activer le filtrage d'avis basé sur le seuil de redirection."),
        ),
    ]
