# Generated by Django 6.0.2 on 2026-02-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0034_alter_etablissement_review_filtering_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='ai_response_malicious_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='ai_response_validation_required',
            field=models.BooleanField(default=False),
        ),
    ]
