# Generated by Django 6.0.2 on 2026-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0035_etablissement_ai_response_malicious_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='locked',
            field=models.BooleanField(default=False, help_text='Empêche la suppression et la modification de certains champs dans le dashboard.'),
        ),
    ]
