# Generated by Django 6.0.2 on 2026-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0036_qrcode_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_show_badge',
            field=models.BooleanField(default=True, help_text='Afficher le badge de destination sur le QR code.'),
        ),
    ]
