# Generated by Django 6.0.2 on 2026-02-15 19:59

from django.db import migrations, models

import apps.private.auths.models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0037_qrcode_qr_show_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_logo',
            field=models.ImageField(blank=True, help_text='Logo à afficher au centre du QR code.', null=True, upload_to=apps.private.auths.models.qr_logo_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.private.auths.models.profile_picture_path),
        ),
    ]
