# Generated by Django 6.0.2 on 2026-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0038_alter_qrcode_qr_logo_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='ai_response_validation_required',
            field=models.BooleanField(default=True),
        ),
    ]
